apiVersion: v1
kind: Secret
metadata:
  name: alethic-ism-state-router-secret
  namespace: alethic
stringData:
#  ROUTING_FILE: "/app/config/routing.yaml/routing.yaml"
  LOG_LEVEL: "DEBUG"
  DATABASE_URL: "postgresql://ism_db_user:ism_db_user@alethic-db-service:5432/ism_db"
  MSG_URL: "pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650"
  MSG_TOPIC: "ism_state_router"
  MSG_MANAGE_TOPIC: "ism_state_router_manage"
  MSG_TOPIC_SUBSCRIPTION: "ism_state_router_subscription"
  .routing.yaml: |
    messageConfig:
        root_route:
          topic: ism_general
          manage_topic: ism_general_manage
          subscription: ism_general_subscription
          service_url: pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650
    
        topic_routes:
          - selector: processor/monitor
            topic: ism_monitor
            manage_topic: ism_monitor_monitor
            subscription: ism_monitor_subscription
            service_url: pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650
    
          - selector: language/models/openai/gpt-4-1106-preview
            topic: ism_openai_qa
            manage_topic: ism_openai_qa_manage
            subscription: ism_openai_qa_subscription
            service_url: pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650
    
          - selector: language/models/openai/gpt-4o-2024-05-13
            topic: ism_openai_qa
            manage_topic: ism_openai_qa_manage
            subscription: ism_openai_qa_subscription
            service_url: pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650
    
          - selector: language/models/openai/gpt-4-turbo-2024-04-09
            topic: ism_openai_qa
            manage_topic: ism_openai_qa_manage
            subscription: ism_openai_qa_subscription
            service_url: pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650
    
          - selector: language/models/openai/gpt-3.5-turbo-0125
            topic: ism_openai_qa
            manage_topic: ism_openai_qa_manage
            subscription: ism_openai_qa_subscription
            service_url: pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650
    
          - selector: language/models/anthropic/claude-3.0
            topic: ism_anthropic_qa
            manage_topic: ism_anthropic_qa_manage
            subscription: ism_anthropic_qa_subscription
            service_url: pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650
    
          - selector: language/models/anthropic/claude-2.0
            topic: ism_anthropic_qa
            manage_topic: ism_anthropic_qa_manage
            subscription: ism_anthropic_qa_subscription
            service_url: pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650
    
          - selector: language/models/anthropic/claude-2.1
            topic: ism_anthropic_qa
            manage_topic: ism_anthropic_qa_manage
            subscription: ism_anthropic_qa_subscription
            service_url: pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650
    
          - selector: language/models/anthropic/claude-3-opus-20240229
            topic: ism_anthropic_qa
            manage_topic: ism_anthropic_qa_manage
            subscription: ism_anthropic_qa_subscription
            service_url: pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650
    
          - selector: code/executor/python/python-executor-1.0
            topic: ism_python_executor
            manage_topic: ism_python_executor_manage
            subscription: ism_python_executor_subscription
            service_url: pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650
    
          - selector: data/transformers/mixer/state-coalescer-1.0
            topic: ism_state_coalescer
            manage_topic: ism_state_coalescer_manage
            subscription: ism_state_coalescer_subscription
            service_url: pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650
